name: Build Battery Discharge APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0

    - name: Cache Gradle Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Make Gradlew Executable
      run: chmod +x ./gradlew

    # Debug build step skipped

    - name: Build Release APK
      run: ./gradlew :app:assembleRelease

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: battery-discharge-release
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
        retention-days: 30

    - name: Create Magisk Module
      run: |
        mkdir -p magisk-module/META-INF/com/google/android
        mkdir -p magisk-module/system/app/BatteryDischarge
        cp ${{steps.sign_app.outputs.signedReleaseFile}} magisk-module/system/app/BatteryDischarge/BatteryDischarge.apk

        # Create module.prop
        cat > magisk-module/module.prop << EOF
        id=battery_discharge_calc
        name=Battery Discharge Calculator
        version=v1.0
        versionCode=1
        author=ExtremeAndroid
        description=Real-time battery discharge calculator for Galaxy S10+ Exynos beyond2lte with live current readings
        minMagisk=20400
        EOF

        # Create service.sh for root access
        cat > magisk-module/service.sh << 'EOF'
        #!/system/bin/sh
        # Grant root permissions to battery discharge app
        pm grant com.batterydischarge.calculator android.permission.WRITE_SECURE_SETTINGS 2>/dev/null
        pm grant com.batterydischarge.calculator android.permission.DUMP 2>/dev/null

        # Set SELinux context for battery access
        chcon u:object_r:sysfs_batteryinfo:s0 /sys/class/power_supply/battery/* 2>/dev/null
        chmod 644 /sys/class/power_supply/battery/current_now 2>/dev/null
        chmod 644 /sys/class/power_supply/battery/charge_full_design 2>/dev/null
        chmod 644 /sys/class/power_supply/battery/capacity 2>/dev/null
        EOF

        # Create install.sh
        cat > magisk-module/install.sh << 'EOF'
        #!/sbin/sh
        ui_print "🔋 Installing Battery Discharge Calculator..."
        ui_print "📱 Optimized for Galaxy S10+ Exynos (beyond2lte)"
        ui_print "⚡ Features: Live current readings, Root integration"
        ui_print "🎯 Compatible with Extreme Kernel & OneUI 7"

        # Install APK as system app
        cp -f $MODPATH/system/app/BatteryDischarge/BatteryDischarge.apk /data/local/tmp/
        pm install -r /data/local/tmp/BatteryDischarge.apk
        rm -f /data/local/tmp/BatteryDischarge.apk

        ui_print "✅ Installation complete!"
        ui_print "   Launch 'Battery Discharge' from app drawer"
        EOF

        # Create update-binary
        cat > magisk-module/META-INF/com/google/android/update-binary << 'EOF'
        #!/sbin/sh
        #################
        # Initialization
        #################
        umask 022
        OUTFD=$2
        ZIPFILE=$3

        mount /data 2>/dev/null

        # Load utility functions
        [ -f /data/adb/magisk/util_functions.sh ] && . /data/adb/magisk/util_functions.sh
        [ $MAGISK_VER_CODE -gt 18100 ] && require_new_magisk || require_new_magisk() { ui_print "*******************************"; ui_print " Please install Magisk v19.0+! "; ui_print "*******************************"; exit 1; }

        #########################
        # Load package installer
        #########################
        LATESTARTSERVICE=true
        REPLACE_EXAMPLE="
        /system/app/Youtube
        /system/priv-app/SystemUI
        "
        REPLACE="
        "

        ##########
        # Custom
        ##########
        set_permissions() {
          set_perm_recursive $MODPATH 0 0 0755 0644
          set_perm_recursive $MODPATH/system/app/BatteryDischarge 0 0 0755 0644
        }

        # Only some special files require specific permissions
        # This function will be called after on_install is done
        # The default permissions should be good enough for most cases

        print_modname() {
          ui_print "🔋 Battery Discharge Calculator"
          ui_print "   Galaxy S10+ Exynos Optimized"
          ui_print "   Version: 1.0"
        }

        on_install() {
          ui_print "- Extracting module files"
          unzip -o "$ZIPFILE" -x 'META-INF/*' -d $MODPATH >&2

          # Run custom install script
          if [ -f $MODPATH/install.sh ]; then
            ui_print "- Running device-specific installation"
            . $MODPATH/install.sh
          fi
        }

        ##############
        # Finalizing
        ##############
        $BOOTMODE || recovery_cleanup
        rm -rf $MODPATH/META-INF 2>/dev/null
        exit 0
        EOF

        # Create updater-script
        cat > magisk-module/META-INF/com/google/android/updater-script << EOF
        #MAGISK
        EOF

        chmod +x magisk-module/META-INF/com/google/android/update-binary
        chmod +x magisk-module/install.sh
        chmod +x magisk-module/service.sh

        # Create ZIP
        cd magisk-module
        zip -r ../battery-discharge-magisk.zip .
        cd ..

    - name: Upload Magisk Module
      uses: actions/upload-artifact@v4
      with:
        name: battery-discharge-magisk
        path: battery-discharge-magisk.zip
        retention-days: 30
