name: Build Battery Discharge APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: platform-tools,platforms;android-34,build-tools;34.0.0

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease

      - name: Upload Unsigned Release APK
        uses: actions/upload-artifact@v4
        with:
          name: battery-discharge-release-unsigned
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 30

      - name: Create Magisk Module
        run: |
          set -e
          mkdir -p magisk-module/{META-INF/com/google/android,system/app/BatteryDischarge}
          cp app/build/outputs/apk/release/app-release.apk magisk-module/system/app/BatteryDischarge/BatteryDischarge.apk

          cat > magisk-module/module.prop <<EOF
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*' '**/gradle-wrapper.properties') }}
name=Battery Discharge Calculator
version=1.0
versionCode=1
author=ExtremeAndroid
description=Real-time battery discharge calculator for Galaxy S10+ Exynos beyond2lte with live current readings
minMagisk=20400
EOF

          cat > magisk-module/service.sh <<'EOF'
#!/system/bin/sh
pm grant com.batterydischarge.calculator android.permission.WRITE_SECURE_SETTINGS 2>/dev/null
pm grant com.batterydischarge.calculator android.permission.DUMP 2>/dev/null
chcon u:object_r:sysfs_batteryinfo:s0 /sys/class/power_supply/battery/* 2>/dev/null
chmod 644 /sys/class/power_supply/battery/current_now 2>/dev/null
chmod 644 /sys/class/power_supply/battery/charge_full_design 2>/dev/null
chmod 644 /sys/class/power_supply/battery/capacity 2>/dev/null
EOF

          cat > magisk-module/install.sh <<'EOF'
#!/sbin/sh
ui_print "🔋 Installing Battery Discharge Calculator..."
ui_print "📱 Optimized for Galaxy S10+ Exynos (beyond2lte)"
ui_print "⚡ Features: Live current readings, Root integration"
cp -f $MODPATH/system/app/BatteryDischarge/BatteryDischarge.apk /data/local/tmp/
pm install -r /data/local/tmp/BatteryDischarge.apk
rm -f /data/local/tmp/BatteryDischarge.apk
ui_print "✅ Installation complete!"
EOF

          cat > magisk-module/META-INF/com/google/android/update-binary <<'EOF'
#!/sbin/sh
umask 022
OUTFD=$2
ZIPFILE=$3
[ -f /data/adb/magisk/util_functions.sh ] && . /data/adb/magisk/util_functions.sh
[ $MAGISK_VER_CODE -le 18100 ] && require_new_magisk
print_modname() {
  ui_print "🔋 Battery Discharge Calculator (v1.0)"
}
on_install() {
  ui_print "- Extracting module files"
  unzip -o "$ZIPFILE" -x 'META-INF/*' -d $MODPATH >&2
  ui_print "- Running install.sh"
  . $MODPATH/install.sh
}
set_permissions() {
  set_perm_recursive $MODPATH 0 0 0755 0644
}
print_modname
on_install
set_permissions
exit 0
EOF

          cat > magisk-module/META-INF/com/google/android/updater-script <<EOF
#MAGISK
EOF

          chmod +x magisk-module/{service.sh,install.sh}
          chmod +x magisk-module/META-INF/com/google/android/update-binary
          cd magisk-module
          zip -r ../battery-discharge-magisk.zip .
          cd - || true

      - name: Upload Magisk Module
        uses: actions/upload-artifact@v4
        with:
          name: battery-discharge-magisk
          path: battery-discharge-magisk.zip
          retention-days: 30
